#!/bin/bash

# rename lecture notes files to make it easier to see which is which.
# currentFormat: lecture_$(date +"%d_%m_%y").txt
# desiredFormat: date +"%Y%m%d_lecture_%A_%d_%B.txt"

index = 1
for arg in "$@"
do
	echo "Arg #$index = $arg"

	IFS='_' read -a array <<< "$arg"
	echo "${array[0]}"
	echo "${array[1]}"
	echo "${array[2]}"
	echo "${array[3]}"

	echo "2014${array[2]}${array[1]}_lecture.txt"
	echo $(date -j -f "%Y%m%d" "2014${array[2]}${array[1]}" "+%Y%m%d_lecture_%A_%d_%B.txt")

	mv "$arg" $(date -j -f "%Y%m%d" "2014${array[2]}${array[1]}" "+%Y%m%d_lecture_%A_%d_%B.txt")

	let "index+=1"
done
